package br.ufes.gerenciaimagens.presenter.principal;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author rborges
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        desktop = new javax.swing.JDesktopPane();
        panelRodape = new javax.swing.JPanel();
        buttonNotificacoes = new javax.swing.JButton();
        labelUsuarioLogado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuImagem = new javax.swing.JMenu();
        itemListarImagem = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        itemManterUsuarios = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerência de Imagens");
        setExtendedState(6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );

        jLabel1.setText("Usuário:");

        javax.swing.GroupLayout panelRodapeLayout = new javax.swing.GroupLayout(panelRodape);
        panelRodape.setLayout(panelRodapeLayout);
        panelRodapeLayout.setHorizontalGroup(
            panelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRodapeLayout.setVerticalGroup(
            panelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRodapeLayout.createSequentialGroup()
                .addGroup(panelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRodapeLayout.createSequentialGroup()
                        .addGroup(panelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buttonNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuImagem.setText("Imagem");

        itemListarImagem.setText("Listar Imagens");
        menuImagem.add(itemListarImagem);

        menuBarPrincipal.add(menuImagem);

        menuUsuario.setText("Usuário");

        itemManterUsuarios.setText("Listar usuários");
        menuUsuario.add(itemManterUsuarios);

        menuBarPrincipal.add(menuUsuario);

        menuSair.setText("Sair");

        itemSair.setText("Sair");
        menuSair.add(itemSair);

        menuBarPrincipal.add(menuSair);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getButtonNotificacoes() {
        return buttonNotificacoes;
    }

    public JMenuItem getItemListarImagem() {
        return itemListarImagem;
    }

    public JMenuItem getItemListarUsuarios() {
        return itemManterUsuarios;
    }

    public JLabel getLabelUsuarioLogado() {
        return labelUsuarioLogado;
    }

    public JDesktopPane getDesktop() {
        return desktop;
    }

    public JPanel getPanelRodape() {
        return panelRodape;
    }

    public JMenuBar getMenuBarPrincipal() {
        return menuBarPrincipal;
    }

    public JMenu getMenuImagem() {
        return menuImagem;
    }

    public JMenu getMenuUsuario() {
        return menuUsuario;
    }

    public JMenuItem getItemSair() {
        return itemSair;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNotificacoes;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem itemListarImagem;
    private javax.swing.JMenuItem itemManterUsuarios;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelUsuarioLogado;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuImagem;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JPanel panelRodape;
    // End of variables declaration//GEN-END:variables
}
