/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.gerenciaimagens.presenter.listaimagem.visualiza;

/**
 *
 * @author rborges
 */
public class VisualizaImagemView extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizaImagemView
     */
    public VisualizaImagemView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCompartilhar = new javax.swing.JButton();
        buttonSolicitarAcesso = new javax.swing.JButton();
        labelMensagemNaoPossuiAcesso = new javax.swing.JLabel();

        setTitle("Visualizar Imagem");

        buttonCompartilhar.setText("Compartilhar");

        buttonSolicitarAcesso.setText("Solicitar acesso de visualização");

        labelMensagemNaoPossuiAcesso.setText("Você não possui acesso de visualização nesta imagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSolicitarAcesso)
                        .addGap(44, 44, 44)
                        .addComponent(buttonCompartilhar))
                    .addComponent(labelMensagemNaoPossuiAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMensagemNaoPossuiAcesso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCompartilhar)
                    .addComponent(buttonSolicitarAcesso))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCompartilhar;
    private javax.swing.JButton buttonSolicitarAcesso;
    private javax.swing.JLabel labelMensagemNaoPossuiAcesso;
    // End of variables declaration//GEN-END:variables
}
