/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.gerenciaimagens.presenter.gerenciarpermissao;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author rborges
 */
public class GerenciarPermissaoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerenciarPermissaoView
     */
    public GerenciarPermissaoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkboxCompartilhar = new javax.swing.JCheckBox();
        checkboxVisualizar = new javax.swing.JCheckBox();
        checkboxExcluir = new javax.swing.JCheckBox();
        labelPermissoesUsuario = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Permissões");

        checkboxCompartilhar.setText("Compartilhar");

        checkboxVisualizar.setText("Visualizar");

        checkboxExcluir.setText("Excluir");

        buttonSalvar.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxCompartilhar)
                    .addComponent(checkboxVisualizar)
                    .addComponent(checkboxExcluir)
                    .addComponent(labelPermissoesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSalvar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPermissoesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxCompartilhar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(buttonSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JCheckBox getCheckboxCompartilhar() {
        return checkboxCompartilhar;
    }

    public JCheckBox getCheckboxExcluir() {
        return checkboxExcluir;
    }

    public JCheckBox getCheckboxVisualizar() {
        return checkboxVisualizar;
    }

    public JLabel getLabelPermissoesUsuario() {
        return labelPermissoesUsuario;
    }

    public JButton getButtonSalvar() {
        return buttonSalvar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JCheckBox checkboxCompartilhar;
    private javax.swing.JCheckBox checkboxExcluir;
    private javax.swing.JCheckBox checkboxVisualizar;
    private javax.swing.JLabel labelPermissoesUsuario;
    // End of variables declaration//GEN-END:variables
}
