/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.gerenciaimagens.presenter.login;

import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author rborges
 */
public class LoginView extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        buttonAcao = new javax.swing.JButton();
        textSenha = new javax.swing.JPasswordField();
        scrollPrimeiroUsuario = new javax.swing.JScrollPane();
        textPrimeiroUsuario = new javax.swing.JTextArea();

        labelLogin.setText("Login");

        labelSenha.setText("Senha");

        buttonAcao.setText("Logar");

        textPrimeiroUsuario.setColumns(20);
        textPrimeiroUsuario.setRows(5);
        scrollPrimeiroUsuario.setViewportView(textPrimeiroUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSenha)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAcao))
                    .addComponent(textLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLogin)
                            .addComponent(labelSenha))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollPrimeiroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPrimeiroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAcao)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getButtonAcao() {
        return buttonAcao;
    }

    public JTextField getTextLogin() {
        return textLogin;
    }

    public JPasswordField getTextSenha() {
        return textSenha;
    }

    public JLabel getLabelLogin() {
        return labelLogin;
    }

    public JTextArea getTextPrimeiroUsuario() {
        return textPrimeiroUsuario;
    }

    public JLabel getLabelSenha() {
        return labelSenha;
    }

    public JScrollPane getScrollPrimeiroUsuario() {
        return scrollPrimeiroUsuario;
    }
    
    public JInternalFrame getInternalFrame() {
        return this;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcao;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JScrollPane scrollPrimeiroUsuario;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextArea textPrimeiroUsuario;
    private javax.swing.JPasswordField textSenha;
    // End of variables declaration//GEN-END:variables
}
