/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.gerenciaimagens.presenter.imagem.visualiza;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author rborges
 */
public class VisualizaImagemView extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizaImagemView
     */
    public VisualizaImagemView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSolicitarAcesso = new javax.swing.JButton();
        labelMensagemNaoPossuiAcesso = new javax.swing.JLabel();
        labelImagem = new javax.swing.JLabel();
        checkboxTodasImagens = new javax.swing.JCheckBox();
        checkboxSomenteNesta = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Visualizar Imagem");

        buttonSolicitarAcesso.setText("Solicitar acesso de visualização");

        labelMensagemNaoPossuiAcesso.setText("Você não possui acesso de visualização nesta imagem. Solicite acesso a essa ou todas imagens");

        labelImagem.setText("Imagem");

        checkboxTodasImagens.setText("Todas imagens");

        checkboxSomenteNesta.setText("Somente nesta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMensagemNaoPossuiAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSolicitarAcesso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkboxSomenteNesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkboxTodasImagens)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMensagemNaoPossuiAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxTodasImagens)
                    .addComponent(checkboxSomenteNesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelImagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(buttonSolicitarAcesso)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public JButton getButtonSolicitarAcesso() {
        return buttonSolicitarAcesso;
    }

    public JLabel getLabelImagem() {
        return labelImagem;
    }

    public JLabel getLabelMensagemNaoPossuiAcesso() {
        return labelMensagemNaoPossuiAcesso;
    }

    public JCheckBox getCheckboxSomenteNesta() {
        return checkboxSomenteNesta;
    }

    public JCheckBox getCheckboxTodasImagens() {
        return checkboxTodasImagens;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSolicitarAcesso;
    private javax.swing.JCheckBox checkboxSomenteNesta;
    private javax.swing.JCheckBox checkboxTodasImagens;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel labelMensagemNaoPossuiAcesso;
    // End of variables declaration//GEN-END:variables
}
