/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.gerenciaimagens.presenter.listaimagem;

import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author rborges
 */
public class ListaImagemView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaImagemView
     */
    public ListaImagemView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listImagem = new javax.swing.JList<>();
        buttonVisualizar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonCompartilhar = new javax.swing.JButton();
        buttonGerenciarPermissoes = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Lista de Imagens");

        jScrollPane1.setViewportView(listImagem);

        buttonVisualizar.setText("Visualizar");

        buttonExcluir.setText("Excluir");

        buttonCompartilhar.setText("Compartilhar");

        buttonGerenciarPermissoes.setText("Gerenciar Permissões");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonGerenciarPermissoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCompartilhar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonVisualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVisualizar)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonCompartilhar)
                    .addComponent(buttonGerenciarPermissoes))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JList<String> getListImagem() {
        return listImagem;
    }

    public JButton getButtonCompartilhar() {
        return buttonCompartilhar;
    }

    public JButton getButtonExcluir() {
        return buttonExcluir;
    }

    public JButton getButtonGerenciarPermissoes() {
        return buttonGerenciarPermissoes;
    }

    public JButton getButtonVisualizar() {
        return buttonVisualizar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCompartilhar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonGerenciarPermissoes;
    private javax.swing.JButton buttonVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listImagem;
    // End of variables declaration//GEN-END:variables
}
